[build]
  publish = "_site"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/404"
  status = 404

[[redirects]]
  from = "/static/img/:file"
  to = "/.netlify/functions/image-cdn?url=/static/img/:file"
  status = 200
